//
// This is a file generated by Phase-Locked Loop wizard.
// Please do not edit this file!
// Generated time: 07/26/2019 14:38:27
// Version: Fuxi 2019.1 win64
// Wizard name: Phase-Locked Loop 1.0b
//
// ============================================================
// File Name: pll_v1.v
// IP core : pll
// Device name: H1D03N3W72C7
// ============================================================

module pll_v1(
    clkin0,
    clkout0,
    clkout1,
    clkout2,
    clkout3,
    locked
);

input clkin0;
output clkout0;
output clkout1;
output clkout2;
output clkout3;
output locked;

PLLV2 #(
        .CFG_SEL_FBPATH (1'b0),
        .CFG_CKSEL (1'b0),
        .CFG_CK_SWITCH_EN (1'b0),
        .CFG_DIVN (8'b00000111),
        .CFG_DIVM (8'b01100110),
        .CFG_DIVFB (1'b0),
        .CFG_LPF (3'b010),
        .CFG_CPSEL_CR (3'b010),
        .CFG_CPSEL_FN (7'b1100110),
        .CFG_CP_AUTO_ENB (1'b0),
        .CFG_RST_REG_ENB (1'b0),
        .CFG_CALIB_EN (1'b1),
        .CFG_CALIB_RSTN (1'b1),
        .CFG_CALIB_MANUAL (4'b1000),
        .CFG_CALIB_WIN (2'b00),
        .CFG_CALIB_DIV (8'b00001010),
        .CFG_CALIB_16_32U (1'b0),
        .CFG_BP_VDOUT (1'b0),
        .CFG_LKD_MUX (1'b0),
        .CFG_FORCE_LOCK (1'b0),
        .CFG_FLDD (2'b11),
        .CFG_ATEST_EN (1'b0),
        .CFG_DTEST_EN (1'b0),
        .CFG_ATEST_SEL (1'b0),
        .CFG_DTEST_SEL (1'b0),
        .CFG_VCO_INI_SEL (1'b0),
        .CFG_LKD_TOL (1'b0),
        .CFG_LKD_HOLD (1'b0),
        .CFG_VRSEL (2'b10),
        .CFG_BK (4'b0001),
        .CFG_SSEN (1'b0),
        .CFG_SSDIVH (2'b00),
        .CFG_SSDIVL (8'b10000100),
        .CFG_SSRG (2'b01),
        .CFG_MKEN0 (1'b1),
        .CFG_MKEN1 (1'b1),
        .CFG_MKEN2 (1'b1),
        .CFG_MKEN3 (1'b1),
        .CFG_MKEN4 (1'b0),
        .CFG_MKEN5 (1'b0),
        .CFG_BPS0 (1'b0),
        .CFG_BPS1 (1'b0),
        .CFG_BPS2 (1'b0),
        .CFG_BPS3 (1'b0),
        .CFG_BPS4 (1'b0),
        .CFG_BPS5 (1'b0),
        .CFG_DIVC0 (8'b00000110),
        .CFG_DIVC1 (8'b01000111),
        .CFG_DIVC2 (8'b00010000),
        .CFG_DIVC3 (8'b00010100),
        .CFG_DIVC4 (8'b00001000),
        .CFG_DIVC5 (8'b00001000),
        .CFG_CO0DLY (8'b00000000),
        .CFG_CO1DLY (8'b00000000),
        .CFG_CO2DLY (8'b00000000),
        .CFG_CO3DLY (8'b00000000),
        .CFG_CO4DLY (8'b00000000),
        .CFG_CO5DLY (8'b00000000),
        .CFG_P0SEL (3'b000),
        .CFG_P1SEL (3'b000),
        .CFG_P2SEL (3'b000),
        .CFG_P3SEL (3'b000),
        .CFG_P4SEL (3'b000),
        .CFG_P5SEL (3'b000),
        .CFG_PFBSEL (3'b000),
        .CFG_RSTPLL_SEL (2'b01),
        .CFG_PPDB_SEL (2'b01),
        .CFG_LOCK_GATE (1'b1),
        .CFG_FRAC (3'b000),
        .CFG_FP_EN (1'b0)
)
pll_u0 (
        .PLLCK0 (clkin0),
        .PLLCK1 (),
        .FBIN (),
        .FP_PLL_PDB (),
        .FP_PLL_RST (),
        .ACTIVECK (),
        .CKBAD0 (),
        .CKBAD1 (),
        .CO0 (clkout0),
        .CO1 (clkout1),
        .CO2 (clkout2),
        .CO3 (clkout3),
        .CO4 (),
        .CO5 (),
        .PLOCK (locked)
);

endmodule

// ============================================================
//                  pll Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : pll_v1
// IP core         : pll
// IP Version      : 1

// AutoSwitch      : false
// BandWidth       : Medium
// Bypass0         : false
// Bypass1         : false
// Bypass2         : false
// Bypass3         : false
// Bypass4         : false
// Bypass5         : false
// C0              : 6
// C1              : 71
// C2              : 16
// C3              : 20
// C4              : 8
// C5              : 8
// Clkin0Enable    : true
// Clkin1Enable    : false
// ClkinDefault    : 0
// Clkout0UseFrac  : true
// ClkoutNum       : 4
// Delay0          : 0
// Delay1          : 0
// Delay2          : 0
// Delay3          : 0
// Delay4          : 0
// Delay5          : 0
// DelayUnit       : degree
// DeskewMode      : None
// Enable0         : true
// Enable1         : true
// Enable2         : true
// Enable3         : true
// Enable4         : false
// Enable5         : false
// ForceLocked     : false
// GclkCcbEnable   : false
// InputFreq       : 80
// M               : 102
// N               : 7
// Phase0          : 0
// Phase1          : 0
// Phase2          : 0
// Phase3          : 0
// Phase4          : 0
// Phase5          : 0
// PortActiveck    : false
// PortCkbad0      : false
// PortCkbad1      : false
// PortLocked      : true
// PowerMode       : always_on
// ResetMode       : ccb
// Simulation Files: 
// SpreadDivH      : 0
// SpreadDivL      : 132
// SpreadEnable    : false
// SpreadRatio     : 1
// Synthesis Files : 
// UseDynPhaseShift: false
// UseLockGate     : false
// VcoCalibration  : true
// VcoDivide       : 0
