//
// This is a file generated by GBuf wizard.
// Please do not edit this file!
// Generated time: 05/10/2019 08:18:36
// Version: Fuxi 2019.1 win64
// Wizard name: GBuf 1.1a
//
// ============================================================
// File Name: gbuf_v1_1.v
// IP core : gbuf
// Device name: H1D03N3W72C7
// ============================================================

module gbuf_v1_1(
    I,
    O
);

input I;
output O;

GBUF u_gbuf (
        .in (I),
        .out (O)
);

endmodule

// ============================================================
//                  gbuf Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : gbuf_v1_1
// IP core         : gbuf
// IP Version      : 1_1

// Simulation Files: 
// Synthesis Files : 
