//
// This is a file generated by MAC wizard.
// Please do not edit this file!
// Generated time: 09/19/2019 17:25:53
// Version: Fuxi 2019.1 win64
// Wizard name: MAC 2.0a
//
// ============================================================
// File Name: h6_mac.v
// IP core : mac
// Device name: H1D03N3W72C7
// ============================================================

module h6_mac(
    mac_out,
    mac_out_cen,
    mac_out_sr,
    dinx,
    diny,
    dinz,
    clk,
    dinz_en
);

output [24:0] mac_out;
input mac_out_cen;
input mac_out_sr;
input [8:0] dinx;
input [5:0] diny;
input [11:0] dinz;
input clk;
input dinz_en;

H6_MAC #(
        .modea_sel (3'b010),
        .modeb_sel (3'b000),
        .adinx_input_mode (1'b0),
        .adiny_input_mode (1'b0),
        .adinz_input_mode (1'b0),
        .amac_output_mode (1'b1),
        .bdinx_input_mode (1'b0),
        .bdiny_input_mode (1'b0),
        .bdinz_input_mode (1'b0),
        .bmac_output_mode (1'b0),
        .a_in_rstn_sel (1'b1),
        .a_in_setn_sel (1'b0),
        .a_sr_syn_sel (1'b1),
        .a_ovf_rstn_sel (1'b0),
        .a_out_rstn_sel (48'b111111111111111111111111111111111111111111111111),
        .a_out_setn_sel (48'b000000000000000000000000000000000000000000000000),
        .b_in_rstn_sel (1'b0),
        .b_in_setn_sel (1'b0),
        .b_sr_syn_sel (1'b0),
        .b_ovf_rstn_sel (1'b0),
        .b_out_rstn_sel (28'b0000000000000000000000000000),
        .b_out_setn_sel (28'b0000000000000000000000000000)
)
mac_u0 (
        .a_mac_out (mac_out[24:0]),
        .b_mac_out (),
        .a_overflow (),
        .b_overflow (),
        .a_dinxy_cen (1'b1),
        .b_dinxy_cen (),
        .a_dinz_cen (1'b1),
        .b_dinz_cen (),
        .a_mac_out_cen (mac_out_cen),
        .b_mac_out_cen (),
        .a_in_sr (1'b1),
        .b_in_sr (),
        .a_out_sr (mac_out_sr),
        .b_out_sr (),
        .a_dinx ({dinx[8], dinx[8], dinx[8], dinx[8], dinx[8], dinx[8:0]}),
        .a_diny ({diny[5], diny[5], diny[5], diny[5], diny[5:0]}),
        .b_dinx (),
        .b_diny (),
        .a_dinz ({dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11], dinz[11:0]}),
        .b_dinz (),
        .clk (clk),
        .a_sload (1'b0),
        .b_sload (),
        .a_acc_en (1'b0),
        .a_dinz_en (dinz_en),
        .b_acc_en (),
        .b_dinz_en ()
);

endmodule

// ============================================================
//                  mac Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : h6_mac
// IP core         : mac
// IP Version      : 2

// Acc             : false
// Add             : true
// InReset         : false
// InResetVal      : 0
// MacOut          : 25
// ModeSelect      : 12x9
// OutMode         : register
// OutReset        : true
// OutResetVal     : 0
// Overflow        : false
// Simulation Files: 
// Sload           : false
// SyncReset       : true
// Synthesis Files : 
// XMode           : bypass
// XType           : signed
// XWidth          : 9
// YMode           : bypass
// YWidth          : 6
// ZMode           : bypass
// ZWidth          : 12
