//
// This is a file generated by 8051 MCU wizard.
// Please do not edit this file!
// Generated time: 09/17/2019 09:49:01
// Version: Fuxi 2019.1 win64
// Wizard name: 8051 MCU 1.0a
//
// ============================================================
// File Name: mcu_v1.v
// IP core : mcu
// Device name: H1D03N3W72C7
// ============================================================

module mcu_v1(
    clkcpu,
    resetn,
    memack,
    mempsack,
    memdatai,
    memdatao_comb,
    memaddr_comb,
    memwr_comb,
    mempswr_comb,
    memrd_comb,
    mempsrd_comb,
    clkcpuen,
    clkperen,
    ro,
    hold,
    holda,
    intoccur,
    waitstaten,
    scli,
    sdai,
    sclo,
    sdao,
    port0i,
    port0o,
    port1i,
    port1o,
    port2i,
    port2o,
    port3i,
    port3o,
    sfrack,
    sfrdatai,
    sfrdatao,
    sfraddr,
    sfrwe,
    sfroe,
    scki,
    scko,
    scktri,
    misoi,
    misoo,
    misotri,
    mosii,
    mosio,
    mositri,
    ssn,
    spssn,
    swd
);

input clkcpu;
input resetn;
input memack;
input mempsack;
input [7:0] memdatai;
output [7:0] memdatao_comb;
output [22:0] memaddr_comb;
output memwr_comb;
output mempswr_comb;
output memrd_comb;
output mempsrd_comb;
output clkcpuen;
output clkperen;
output ro;
input hold;
output holda;
output intoccur;
output waitstaten;
input scli;
input sdai;
output sclo;
output sdao;
input [7:0] port0i;
output [7:0] port0o;
input [7:0] port1i;
output [7:0] port1o;
input [7:0] port2i;
output [7:0] port2o;
input [7:0] port3i;
output [7:0] port3o;
input sfrack;
input [7:0] sfrdatai;
output [7:0] sfrdatao;
output [6:0] sfraddr;
output sfrwe;
output sfroe;
input scki;
output scko;
output scktri;
input misoi;
output misoo;
output misotri;
input mosii;
output mosio;
output mositri;
input ssn;
output [7:0] spssn;
input swd;

h6_r8051xc2 #( .program_file ("../51_rx_pinf_tx_pinf_1080_reverse/Objects/mipi_rx_pinf_tx_pinf_1080.hex") ) u_h6_8051 (
        .clkcpu (clkcpu),
        .resetn (resetn),
        .clkper (clkcpu),
        .memack (memack),
        .mempsack (mempsack),
        .memdatai (memdatai),
        .memdatao_comb (memdatao_comb),
        .memaddr_comb (memaddr_comb),
        .memwr_comb (memwr_comb),
        .mempswr_comb (mempswr_comb),
        .memrd_comb (memrd_comb),
        .mempsrd_comb (mempsrd_comb),
        .clkcpuen (clkcpuen),
        .clkperen (clkperen),
        .ro (ro),
        .hold (hold),
        .holda (holda),
        .intoccur (intoccur),
        .waitstaten (waitstaten),
        .scli (scli),
        .sdai (sdai),
        .sclo (sclo),
        .sdao (sdao),
        .port0i (port0i),
        .port0o (port0o),
        .port1i (port1i),
        .port1o (port1o),
        .port2i (port2i),
        .port2o (port2o),
        .port3i (port3i),
        .port3o (),
        .sfrack (sfrack),
        .sfrdatai (sfrdatai),
        .sfrdatao (sfrdatao),
        .sfraddr (sfraddr),
        .sfrwe (sfrwe),
        .sfroe (sfroe),
        .scki (scki),
        .scko (scko),
        .scktri (scktri),
        .misoi (misoi),
        .misoo (misoo),
        .misotri (misotri),
        .mosii (mosii),
        .mosio (mosio),
        .mositri (mositri),
        .ssn (ssn),
        .spssn (spssn),
        .swd (swd)
);

endmodule

// ============================================================
//                  mcu Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : mcu_v1
// IP core         : mcu
// IP Version      : 1

// InitFile        : ../51_rx_pinf_tx_pinf_1080_reverse/Objects/mipi_rx_pinf_tx_pinf_1080.hex
// Simulation Files: 
// Synthesis Files : 
// UseGlobalSignal : true
// UseHoldMode     : true
// UseI2C          : true
// UsePort0        : true
// UsePort1        : true
// UsePort2        : true
// UsePort3        : true
// UseSfr          : true
// UseSpi          : true
// UseWatchDog     : true
