//
// This is a file generated by Power On Reset wizard.
// Please do not edit this file!
// Generated time: 07/08/2019 10:31:29
// Version: Fuxi 2019.1 win64
// Wizard name: Power On Reset 1.1a
//
// ============================================================
// File Name: por_v1_1.v
// IP core : por
// Device name: H1D03N3W72C7
// ============================================================

module por_v1_1(
    O
);

output O;

USERPORV1 u_por (
        .por (O)
);

endmodule

// ============================================================
//                  por Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : por_v1_1
// IP core         : por
// IP Version      : 1_1

// Simulation Files: 
// Synthesis Files : 
