//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 09/05/2019 15:39:05
// Version: Fuxi 2019.1 win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: tx_data_fifo.v
// IP core : fifo
// Device name: H1D03N3W72C7
// ============================================================

module tx_data_fifo(
    wclk,
    rclk,
    rrst_n,
    wrst_n,
    wdata,
    rdata,
    wen,
    ren,
    prog_empty,
    rempty,
    wfull
);

input wclk;
input rclk;
input rrst_n;
input wrst_n;
input [31:0] wdata;
output [31:0] rdata;
input wen;
input ren;
output prog_empty;
output rempty;
output wfull;





fifo_32_1k #(
	.ALMOSTEMPTYTH(10'd810)
)
uut_fifo_32_1k(
	.wclk(wclk),
	.rclk(rclk),
	.rrst_n(rrst_n),
	.wrst_n(wrst_n),
	.wdata(wdata),
	.rdata(rdata),
	.wen(wen),
	.ren(ren),
	.almost_empty(),
	.prog_empty(prog_empty),
	.rempty(rempty),
	.wfull(wfull)
);


endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : tx_data_fifo
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : false
// AlmostFull      : false
// EmptyAssert     : 30
// EmptyNegate     : 20
// EmptySingle     : 810
// EmptyType       : 1
// FifoType        : software
// FullAssert      : 1018
// FullNegate      : 1014
// FullSingle      : 1020
// FullType        : 0
// Fwft            : true
// OverFlow        : false
// PeekMode        : false
// ReadAck         : false
// ReadAddrWidth   : 10
// ReadClr         : false
// ReadCnt         : true
// ReadDataWidth   : 32
// Regout          : false
// RegoutEn        : false
// Simulation Files: ../ip_core/fifo_v2/src/syn_fifo.v ../ip_core/fifo_v2/src/asyn_fifo.v
// Synthesis Files : src/syn_fifo.v src/asyn_fifo.v
// UnderFlow       : false
// UseHardWare     : false
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 10
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 32
// WriteDrop       : false
