create_clock -period 6.66667 -name {u_pll_pll_u0/CO0} [get_pins {u_pll_pll_u0/CO0}]
create_clock -period 50 -name {u_pll_pll_u0/CO1} [get_pins {u_pll_pll_u0/CO1}]
create_clock -period 16.6667 -name {u_pll_pll_u0/CO2} [get_pins {u_pll_pll_u0/CO2}]
create_clock -disable -period 6.66667 -name {mipi_inst_u_mipi2/clk} [get_pins {mipi_inst_u_mipi2/clk}]
create_clock -period 20 -name {u_pll_pll_u0/CO3} [get_pins {u_pll_pll_u0/CO3}]
create_clock -period 6.66667 -name {u0_mipi1_clkdly_genblk1_0__u_mipi_clkdly/xy} [get_pins {u0_mipi1_clkdly_genblk1_0__u_mipi_clkdly/xy}]
create_clock -period 6.66667 -name {u_pll_pll_u0/CO4} [get_pins {u_pll_pll_u0/CO4}]
set_false_path -from [get_clocks {u_pll_pll_u0/CO3}] -to [get_clocks {u_pll_pll_u0/CO0}]
set_false_path -from [get_clocks {mipi_inst_u_mipi2/clk}] -to [get_clocks {u_pll_pll_u0/CO0}]
set_false_path -from [get_clocks {mipi_inst_u_mipi2/clk}] -to [get_clocks {u_pll_pll_u0/CO3}]
set_false_path -from [get_clocks {u_pll_pll_u0/CO0}] -to [get_clocks {mipi_inst_u_mipi2/clk}]
set_false_path -from [get_clocks {u_pll_pll_u0/CO3}] -to [get_clocks {mipi_inst_u_mipi2/clk}]
create_clock -period 3 -name {auto_0_OSC_clk} [get_pins {u_osc/OSC}]
create_clock -period 3 -name {auto_1_out_clk} [get_pins {u_gbuf_u_gbuf/out}]
