//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 08/29/2019 16:27:00
// Version: Fuxi 2019.1 win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: fifo_v2.v
// IP core : fifo
// Device name: H1D03N3W72C7
// ============================================================

module hard_fifos_18x10(
    dout,
    din,
    writeclk,
    readclk,
    writeen,
    readen,
    reset,
    full,
    empty,
    almostempty,
    regce
);

parameter almostemptyth = 10'b1000000000;
parameter peek = 1'b0;
parameter outreg = 1'b0;

output [15:0] dout;
input [15:0] din;
input writeclk;
input readclk;
input writeen;
input readen;
input reset;
output full;
output empty;
output almostempty;
input regce;
wire [17:0] id,od;
assign id = {2'b00,din};
assign dout = od[15:0];
FIFO18K #(
        .almostemptyth (almostemptyth),
        .almostfullth (10'b1111011100),
        .writewidth (18),
        .readwidth (18),
        .outreg (outreg),
        .peek (peek),
        .readclk_inv (1'b0),
        .writeclk_inv (1'b0),
        .use_parity (1'b0)
)
u_inst (
//        .dout (dout[15:0]),
//        .din (din[15:0]),
        .dout (od),
        .din (id),
        .doutp (),
        .dinp (2'b00),
        .writeclk (writeclk),
        .readclk (readclk),
        .writeen (~writeen),
        .readen (~readen),
        .reset (~reset),
        .full (full),
        .empty (empty),
        .almostempty (almostempty),
        .writesave (0),
        .writedrop (0),
        .regce (regce),
        .eccindberr (0),
        .eccinsberr (0)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : fifo_v2
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : true
// AlmostFull      : false
// EmptyAssert     : 54
// EmptyNegate     : 36
// EmptySingle     : 512
// EmptyType       : 1
// FifoType        : hardware
// FullAssert      : 988
// FullNegate      : 970
// FullSingle      : 988
// FullType        : 0
// Fwft            : false
// OverFlow        : false
// PeekMode        : true
// ReadAck         : false
// ReadAddrWidth   : 10
// ReadClr         : false
// ReadCnt         : false
// ReadDataWidth   : 18
// Regout          : true
// RegoutEn        : true
// Simulation Files: 
// Synthesis Files : 
// UnderFlow       : false
// UseHardWare     : true
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 10
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 18
// WriteDrop       : false
