//
// This is a file generated by Clock Switch wizard.
// Please do not edit this file!
// Generated time: 10/21/2019 19:08:13
// Version: Fuxi 2019.1 win64
// Wizard name: Clock Switch 1.0b
//
// ============================================================
// File Name: clkctrlswitch_0.v
// IP core : clkctrlswitch
// Device name: H1D03N0L144C7
// ============================================================

module clkctrlswitch_0(
    clkin0,
    clkin1,
    fp_sel,
    clkout
);

input clkin0;
input clkin1;
input fp_sel;
output clkout;

CFG_DYN_SWITCH_S2 #(
        .SEL (2'b11),
        .gclk_mux (0)
)
u_clkswitch (
        .o (clkout),
        .i0 (clkin0),
        .i1 (clkin1),
        .fpsel (fp_sel)
);

endmodule

// ============================================================
//                  clkctrlswitch Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : clkctrlswitch_0
// IP core         : clkctrlswitch
// IP Version      : 1

// Mux             : 0
// Simulation Files: 
// Synthesis Files : 
