//
// This is a file generated by Clock Switch wizard.
// Please do not edit this file!
// Generated time: 11/16/2019 14:01:02
// Version: Fuxi 2018a.0 win64
// Wizard name: Clock Switch 1.0b
//
// ============================================================
// File Name: clkctrlswitch_2.v
// IP core : clkctrlswitch
// Device name: H1D03N0L144C7
// ============================================================

module clkctrlswitch_2(
    clkin0,
    clkin1,
    fp_sel,
    clkout
);

input clkin0;
input clkin1;
input fp_sel;
output clkout;

CFG_DYN_SWITCH_S2 #(
        .SEL (2'b11),
        .gclk_mux (2)
)
u_clkswitch (
        .o (clkout),
        .i0 (clkin0),
        .i1 (clkin1),
        .fpsel (fp_sel)
);

endmodule

// ============================================================
//                  clkctrlswitch Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : clkctrlswitch_2
// IP core         : clkctrlswitch
// IP Version      : 1

// Mux             : 2
// Simulation Files: 
// Synthesis Files : 
