//
// This is a file generated by DDRIO wizard.
// Please do not edit this file!
// Generated time: 10/11/2019 15:31:52
// Version: Fuxi 2019.1 win64
// Wizard name: DDRIO 1.0a
//
// ============================================================
// File Name: ddrio_v1.v
// IP core : ddrio
// Device name: H1D03N0L144C7
// ============================================================

module ddrio_v1(
    clk,
    clk_en,
    odp,
    odn,
    idp,
    idn,
    oen,
    pad_out,
    pad
);

input clk;
input clk_en;
input odp;
input odn;
output idp;
output idn;
output pad_out;
input oen;
inout pad;

ddr_io_r #(
        .oen_sel (2'b11),
        .od_sel (2'b10),
        .is_oen_reg (1'b0),
        .is_clk_gate_en (1'b1),
        .is_setn_inv (1'b0),
        .is_setn_sync (1'b0),
        .is_oen_setn_en (1'b0),
        .is_od_setn_en (1'b0),
        .is_id_setn_en (1'b0),
        .is_rstn_inv (1'b0),
        .is_rstn_sync (1'b0),
        .is_oen_rstn_en (1'b0),
        .is_od_rstn_en (1'b0),
        .is_id_rstn_en (1'b0)
)
u_inst (
        .clk (clk),
        .clk_en (clk_en),
        .setn (),
        .rstn (),
        .idp (idp),
        .idn (idn),
        .odp (odp),
        .odn (odn),
        .oen (oen),
        .pad_out (pad_out),
        .pad (pad)
);

endmodule

// ============================================================
//                  ddrio Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : ddrio_v1
// IP core         : ddrio
// IP Version      : 1

// Clock Gating Enabled: true
// IO Direction    : Inout
// IO Register Reset Enabled: false
// IO Register Set Enabled: false
// IO Reset Mode   : Synchronous
// IO Set Mode     : Synchronous
// Simulation Files: 
// Synthesis Files : 
