//
// This is a file generated by Delay Buf wizard.
// Please do not edit this file!
// Generated time: 07/03/2019 11:31:04
// Version: Fuxi 2019.1 win64
// Wizard name: Delay Buf 1.1a
//
// ============================================================
// File Name: delaybuf_v1_1.v
// IP core : delaybuf
// Device name: H1D03N3W72C7
// ============================================================

module delaybuf_v1_1(
    I,
    O
);

input I;
output O;

DELAY_BUF u_delaybuf (
        .in (I),
        .out (O)
);

endmodule

// ============================================================
//                  delaybuf Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : delaybuf_v1_1
// IP core         : delaybuf
// IP Version      : 1_1

// Simulation Files: 
// Synthesis Files : 
