//
// This is a file generated by EMB wizard.
// Please do not edit this file!
// Generated time: 12/16/2019 10:29:53
// Version: Fuxi fuxi win64
// Wizard name: EMB 1.0b
//
// ============================================================
// File Name: emb_bta.v
// IP core : emb
// Device name: H1D03N0L144C7
// ============================================================

module emb_bta (clk, ce, we, rstn, regce, a, d, q);
input clk;
input ce;
input we;
input rstn;
input regce;
input [5:0]a;
input [31:0]d;
output [31:0]q;

wire gnd_net;

assign gnd_net = 0;
EMB9K #(
		.emb5k_1_init_file ("src/emb_bta.dat_0"),
		.emb5k_2_init_file ("src/emb_bta.dat_1"),
		.init_file ("none"),
		.clka_inv (1'b0),
		.clkb_inv (1'b0),
		.extension_mode ("area"),
		.outreg_a (1'b1),
		.outreg_b (1'b0),
		.rammode ("sp"),
		.use_parity (1'b0),
		.width_a (36),
		.width_b (36),
		.writemode_a ("write_first"),
		.writemode_b ("write_first"),
		.byte_write_enable (1'b0)
	)
	emb_0(
		.doa({q[31], q[30], q[29], q[28], q[27], q[26], q[25], q[24], q[23], q[22], q[21], q[20], q[19], q[18], q[17], q[16], q[15], q[14], q[13], q[12], q[11], q[10], q[9], q[8], q[7], q[6], q[5], q[4], q[3], q[2], q[1], q[0]}),
		.dob(),
		.dopa(),
		.dopb(),
		.addra({gnd_net, gnd_net, gnd_net, gnd_net, gnd_net, gnd_net, gnd_net, a[5], a[4], a[3], a[2], a[1], a[0]}),
		.addrb(),
		.clka(clk),
		.clkb(),
		.dia({d[31], d[30], d[29], d[28], d[27], d[26], d[25], d[24], d[23], d[22], d[21], d[20], d[19], d[18], d[17], d[16], d[15], d[14], d[13], d[12], d[11], d[10], d[9], d[8], d[7], d[6], d[5], d[4], d[3], d[2], d[1], d[0]}),
		.dib(),
		.dipa(),
		.dipb(),
		.cea(ce),
		.ceb(gnd_net),
		.regcea(regce),
		.regceb(),
		.regsra(rstn),
		.regsrb(),
		.wea({we, we}),
		.web()
	);
endmodule


// ============================================================
//                  emb Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : emb_bta
// IP core         : emb
// IP Version      : 1

// AddrUsedA       : 6
// ByteWriteEn     : false
// DataUsedA       : 32
// DataUsedB       : 32
// EmbResource     : EMB9K
// EmbType         : sp
// ErrorInjectMode : None
// InitFile        : src/emb_bta.dat
// RegoutA         : true
// RegoutB         : false
// RegoutEnA       : true
// RegoutEnB       : false
// Simulation Files: 
// SplitInfo       : 32,64;block_0:16,256,0,0,0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15;block_1:16,256,0,0,16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
// Synthesis Files : 
// UseEccEn        : false
// WriteModeA      : Write First
// WriteModeB      : Write First
