//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 11/14/2019 16:51:01
// Version: Fuxi 2018a.0 win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: fifo_mipi_rx.v
// IP core : fifo
// Device name: H1D03N0L144C7
// ============================================================

module fifo_mipi_rx(
    dout,
    din,
    writeclk,
    readclk,
    writeen,
    readen,
    reset,
    full,
    empty,
    regce
);

output [35:0] dout;
input [35:0] din;
input writeclk;
input readclk;
input writeen;
input readen;
input reset;
output full;
output empty;
input regce;

FIFO9K #(
        .almostemptyth (5'b00010),
        .almostfullth (5'b00010),
        .writewidth (36),
        .readwidth (36),
        .outreg (1'b1),
        .peek (1'b1),
        .readclk_inv (1'b0),
        .writeclk_inv (1'b0),
        .use_parity (1'b1)
)
u_inst (
        .dout (dout[31:0]),
        .doutp (dout[35:32]),
        .din (din[31:0]),
        .dinp (din[35:32]),
        .writeclk (writeclk),
        .readclk (readclk),
        .writeen (~writeen),
        .readen (~readen),
        .reset (~reset),
        .full (full),
        .empty (empty),
        .writesave (0),
        .writedrop (0),
        .regce (regce)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : fifo_mipi_rx
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : false
// AlmostFull      : false
// EmptyAssert     : 3
// EmptyNegate     : 2
// EmptySingle     : 2
// EmptyType       : 0
// FifoType        : hardware
// FullAssert      : 3
// FullNegate      : 2
// FullSingle      : 2
// FullType        : 0
// Fwft            : false
// OverFlow        : false
// PeekMode        : true
// ReadAck         : false
// ReadAddrWidth   : 5
// ReadClr         : false
// ReadCnt         : false
// ReadDataWidth   : 36
// Regout          : true
// RegoutEn        : true
// Simulation Files: 
// Synthesis Files : 
// UnderFlow       : false
// UseHardWare     : true
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 5
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 36
// WriteDrop       : false
