//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 10/12/2019 17:54:46
// Version: Fuxi 2019.1 win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: fifo_psram_io_rd.v
// IP core : fifo
// Device name: H1D03N0L144C7
// ============================================================

module fifo_psram_io_rd(
    dout,
    din,
    writeclk,
    readclk,
    writeen,
    readen,
    reset,
    full,
    empty,
    almostfull,
    almostempty
);

output [17:0] dout;
input [17:0] din;
input writeclk;
input readclk;
input writeen;
input readen;
input reset;
output full;
output empty;
output almostfull;
output almostempty;

FIFO5K #(
        .almostemptyth (5'b00010),
        .almostfullth (5'b00010),
        .writewidth (18),
        .readwidth (18),
        .outreg (1'b0),
        .peek (1'b0),
        .readclk_inv (1'b0),
        .writeclk_inv (1'b0)
)
u_inst (
        .dout (dout[15:0]),
        .doutp (dout[17:16]),
        .din (din[15:0]),
        .dinp (din[17:16]),
        .writeclk (writeclk),
        .readclk (readclk),
        .writeen (~writeen),
        .readen (~readen),
        .reset (~reset),
        .full (full),
        .empty (empty),
        .almostfull (almostfull),
        .almostempty (almostempty),
        .writesave (0),
        .writedrop (0)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : fifo_psram_io_rd
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : true
// AlmostFull      : true
// EmptyAssert     : 3
// EmptyNegate     : 2
// EmptySingle     : 2
// EmptyType       : 1
// FifoType        : hardware
// FullAssert      : 3
// FullNegate      : 2
// FullSingle      : 2
// FullType        : 1
// Fwft            : false
// OverFlow        : false
// PeekMode        : false
// ReadAck         : false
// ReadAddrWidth   : 5
// ReadClr         : false
// ReadCnt         : false
// ReadDataWidth   : 18
// Regout          : false
// RegoutEn        : false
// Simulation Files: 
// Synthesis Files : 
// UnderFlow       : false
// UseHardWare     : true
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 5
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 18
// WriteDrop       : false
