//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 12/16/2019 14:16:22
// Version: Fuxi fuxi win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: fifo_psram_lbuf_rd.v
// IP core : fifo
// Device name: H1D03N0L144C7
// ============================================================

module fifo_psram_lbuf_rd(
    dout,
    din,
    writeclk,
    readclk,
    writeen,
    readen,
    reset,
    full,
    empty,
    almostfull
);

output [35:0] dout;
input [17:0] din;
input writeclk;
input readclk;
input writeen;
input readen;
input reset;
output full;
output empty;
output almostfull;

FIFO9K #(
        .almostemptyth (8'b00000010),
        .almostfullth (9'b011001000),
        .writewidth (18),
        .readwidth (36),
        .outreg (1'b0),
        .peek (1'b0),
        .readclk_inv (1'b0),
        .writeclk_inv (1'b0),
        .use_parity (1'b1)
)
u_inst (
        .dout (dout[31:0]),
        .doutp (dout[35:32]),
        .din (din[15:0]),
        .dinp (din[17:16]),
        .writeclk (writeclk),
        .readclk (readclk),
        .writeen (~writeen),
        .readen (~readen),
        .reset (~reset),
        .full (full),
        .empty (empty),
        .almostfull (almostfull),
        .writesave (0),
        .writedrop (0)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : fifo_psram_lbuf_rd
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : false
// AlmostFull      : true
// EmptyAssert     : 3
// EmptyNegate     : 2
// EmptySingle     : 2
// EmptyType       : 0
// FifoType        : hardware
// FullAssert      : 6
// FullNegate      : 4
// FullSingle      : 200
// FullType        : 1
// Fwft            : false
// OverFlow        : false
// PeekMode        : false
// ReadAck         : false
// ReadAddrWidth   : 8
// ReadClr         : false
// ReadCnt         : false
// ReadDataWidth   : 36
// Regout          : false
// RegoutEn        : false
// Simulation Files: 
// Synthesis Files : 
// UnderFlow       : false
// UseHardWare     : true
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 9
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 18
// WriteDrop       : false
