//
// This is a file generated by SPI Interface wizard.
// Please do not edit this file!
// Generated time: 11/23/2019 10:41:22
// Version: Fuxi 2018a.0 win64
// Wizard name: SPI Interface 1.0a
//
// ============================================================
// File Name: spiInterface_v1.v
// IP core : spiInterface
// Device name: H1D03N0L144C7
// ============================================================

module spiInterface_v1(
    sclk,
    sdo,
    cson,
    sdi
);

input sclk;
output sdo;
input cson;
input sdi;

spi_interface u_spi_interface (
        .sclk (sclk),
        .sdo (sdo),
        .cson (cson),
        .sdi (sdi)
);

endmodule

// ============================================================
//                  spiInterface Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : spiInterface_v1
// IP core         : spiInterface
// IP Version      : 1

// Simulation Files: 
// Synthesis Files : 
