//
// This is a file generated by SRAM wizard.
// Please do not edit this file!
// Generated time: 02/21/2020 15:02:17
// Version: Fuxi fuxi win64
// Wizard name: SRAM 1.0b
//
// ============================================================
// File Name: sram_v2.v
// IP core : sram
// Device name: H1D03N0L144C7
// ============================================================

module sram_v2(
    clk,
    ceb,
    web,
    datai,
    addr,
    datao
);

input clk;
input ceb;
input web;
input [31:0] datai;
input [10:0] addr;
output [31:0] datao;

SPRAM_2Kx32 #( .init_file ("src/emb_2340_1080_to_1560_720.dat") ) u_spram (
        .clk (clk),
        .ceb (ceb),
        .web (web),
        .datai (datai),
        .addr (addr),
        .datao (datao)
);

endmodule

// ============================================================
//                  sram Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N0L144C7
// Module          : sram_v2
// IP core         : sram
// IP Version      : 1

// Initial_File    : src/emb_2340_1080_to_1560_720.dat
// Simulation Files: 
// Synthesis Files : 
// Type            : 0
