//
// This is a file generated by FIFO wizard.
// Please do not edit this file!
// Generated time: 12/18/2019 19:01:23
// Version: Fuxi 2019.1 win64
// Wizard name: FIFO 2.0a
//
// ============================================================
// File Name: sync_fifo.v
// IP core : fifo
// Device name: H1D03N3W72C7
// ============================================================

module sync_fifo(
    wclk,
    rclk,
    rrst_n,
    wrst_n,
    wdata,
    rdata,
    wen,
    ren,
    rempty,
    wfull
);

input wclk;
input rclk;
input rrst_n;
input wrst_n;
input [3:0] wdata;
output [3:0] rdata;
input wen;
input ren;
output rempty;
output wfull;

wire clkw;
assign clkw = wclk;
wire clkr;
assign clkr = rclk;
wire cew;
wire cer;
wire [2:0] ar;
wire [2:0] aw;
wire [3:0] dw;
wire [3:0] qr;

sync_fifo_emb_v1 u_inst (
        .ar (ar),
        .aw (aw),
        .clkr (clkr),
        .clkw (clkw),
        .cer (cer),
        .cew (cew),
        .dw (dw),
        .qr (qr),
        .rstnr (rrst_n)
);

cme_ip_asyn_fifo_v2 #(
        .wr_dw (4),
        .rd_dw (4),
        .wr_aw (3),
        .rd_aw (3),
        .wr_depth (8),
        .rd_depth (8),
        .fwft_en (1'b0),
        .tDLY (0),
        .gen_prog_full_type (3'b000),
        .gen_prog_empty_type (3'b000),
        .prog_full_const (2),
        .prog_empty_const (2),
        .prog_full_assert_const (3),
        .prog_full_negate_const (2),
        .prog_empty_assert_const (3),
        .prog_empty_negate_const (2),
        .gen_almost_full (1'b0),
        .gen_almost_empty (1'b0),
        .gen_prog_full (1'b0),
        .gen_prog_empty (1'b0),
        .gen_wr_data_cnt (1'b0),
        .gen_rd_data_cnt (1'b0),
        .gen_wr_ack (1'b0),
        .gen_rd_ack (1'b0),
        .gen_wr_overflow (1'b0),
        .gen_rd_underflow (1'b0),
        .need_syn_wr_clr (1'b0),
        .need_syn_rd_clr (1'b0)
)
u_asyn_fifo (
        .wclk (wclk),
        .rclk (rclk),
        .rrst_n (rrst_n),
        .wrst_n (wrst_n),
        .wclr (),
        .rclr (),
        .wdata (wdata),
        .rdata (rdata),
        .wen (wen),
        .ren (ren),
        .almost_full (),
        .almost_empty (),
        .prog_full (),
        .prog_empty (),
        .wr_data_cnt (),
        .rd_data_cnt (),
        .rempty (rempty),
        .wfull (wfull),
        .prog_full_thresh (),
        .prog_empty_thresh (),
        .prog_full_assert (),
        .prog_full_negate (),
        .prog_empty_assert (),
        .prog_empty_negate (),
        .wr_ack (),
        .rd_ack (),
        .overflow (),
        .underflow (),
        .mem_waddr (aw),
        .mem_wdata (dw),
        .mem_cew (cew),
        .mem_cer (cer),
        .mem_raddr (ar),
        .mem_rdata (qr)
);

endmodule

// ============================================================
//                  fifo Setting
//
// Warning: This part is read by Fuxi, please don't modify it.
// ============================================================
// Device          : H1D03N3W72C7
// Module          : sync_fifo
// IP core         : fifo
// IP Version      : 2

// AlmostEmpty     : false
// AlmostFull      : false
// EmptyAssert     : 3
// EmptyNegate     : 2
// EmptySingle     : 2
// EmptyType       : 0
// FifoType        : software
// FullAssert      : 3
// FullNegate      : 2
// FullSingle      : 2
// FullType        : 0
// Fwft            : false
// OverFlow        : false
// PeekMode        : false
// ReadAck         : false
// ReadAddrWidth   : 3
// ReadClr         : false
// ReadCnt         : false
// ReadDataWidth   : 4
// Regout          : false
// RegoutEn        : false
// Simulation Files: ../ip_core/fifo_v2/src/syn_fifo.v ../ip_core/fifo_v2/src/asyn_fifo.v
// Synthesis Files : src/syn_fifo.v src/asyn_fifo.v
// UnderFlow       : false
// UseHardWare     : false
// WorkMode        : true
// WriteAck        : false
// WriteAddrWidth  : 3
// WriteClr        : false
// WriteCnt        : false
// WriteDataWidth  : 4
// WriteDrop       : false
